# Generated by Django 4.2 on 2025-03-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='Код подтверждения')),
                ('destination', models.CharField(max_length=100, verbose_name='Телефон/почта')),
                ('type', models.CharField(choices=[('EMAIL', 'email'), ('PHONE', 'phone')], max_length=5, verbose_name='Куда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('expired_at', models.DateTimeField(verbose_name='Время действия')),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
