# Generated by Django 4.2 on 2025-03-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verificationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verificationcode',
            options={'verbose_name': 'Код верификации', 'verbose_name_plural': 'Коды верификации'},
        ),
    ]
