# Generated by Django 4.2 on 2025-03-30 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'мужчина'), ('FEMALE', 'женщина')], max_length=6, null=True, verbose_name='Пол'),
        ),
    ]
